### ISSUE TITLE
'Visits' panel not rendering correctly

### ISSUE THREAD

**Issue by ansomerv** [grafana/faro#5]
When refreshing the page on a sample app instrumented with Faro, data is sent to grafana cloud but the "visits' panel does not update on each refresh.  

Additionally the panel itself has a maximum scale of 2.
<img width="1403" alt="Screenshot 2023-03-23 at 10 26 53 AM" src="https://user-images.githubusercontent.com/97468854/227249500-2e273bd8-c467-4485-964a-29f89d60fd34.png">

**Comment by cedricziel** [comment]
Hi @ansomerv , this was fixed and massively overhauled end of March. Sorry for getting back so late
